# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Blog Test
tagline:          Some Test Based on Poole
url:              http://blog.fun
paginate:         1
baseurl:          /
author:
  name:           Òscar Vilaplana
  url:            http://oscarvilaplana.cat
  email:          dev@oscarvilaplana.cat

pages_list:
  About: '/about'
  Archive: '/archive'

# Custom vars
version:          1.0.0
github:
  repo:           <http></http>s://github.com/poole/poole
